[msbuild]
project = "Idnaf.LazyOpenSearch.csproj"
configuration = "Release"

[github]
user = "fandigunawan"
repo = "Idnaf.LazyOpenSearch"
version_prefix = "v"

[nuget]
publish = false

[brew]
publish = false

[scoop]
publish = false